name: R2S OpenWrt

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ssh_debug: false

    strategy:
      matrix:
        version: ['SelfUse', 'WithFeatures']
      fail-fast: false

    steps:

      - name: Setup timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: Asia/Shanghai

      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master

      - name: Set Username
        id: set_name
        run: |
          if [ "$GITHUB_ACTOR" = "gyj1109" ];then
            echo "##[set-output name=username;]Gyj1109"
          else
            echo "##[set-output name=username;]$GITHUB_ACTOR"
          fi

      - name: Init build dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi $(docker images -q)
          sudo -E apt-get remove -y --purge azure-cli ghc zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
          sudo -E apt-get update -y
          sudo -E apt-get install -y build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs git-core gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libreadline-dev libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint ccache curl wget vim nano python python3 python-pip python3-pip python-ply python3-ply haveged lrzsz device-tree-compiler scons
          wget -O - https://raw.githubusercontent.com/friendlyarm/build-env-on-ubuntu-bionic/master/install.sh | bash
          sudo -E apt-get autoremove -y --purge
          sudo -E apt-get clean -y
          sudo -E rm -rf /usr/share/dotnet /etc/mysql /etc/php
          git clone https://github.com/friendlyarm/repo
          sudo cp repo/repo /usr/bin/

      - name: Free Disk Space
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile
          sudo apt clean
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Prepare Mixedwrt
        run: |
          sudo chown -R runner:runner /home/runner/work/$(echo $GITHUB_REPOSITORY | sed 's/.*\/\([^:]*\)$/\1/')
          cp -r ./SCRIPTS/. ./
          /bin/bash 01_get_ready.sh

      - name: Prepare Package
        run: |
          cd openwrt
          cp -r ../SCRIPTS/. ./
          /bin/bash 02_prepare_package.sh

      - name: Convert Translation
        run: |
          cd openwrt
          /bin/bash 03_convert_translation.sh

      - name: Remove Upx
        run: |
          cd openwrt
          /bin/bash 04_remove_upx.sh

      - name: Generate config
        run: |
          sed -e '/^##.*$/d' -e '/^$/d' config.seed > openwrt/.config

      - name: Generate addon config
        if: matrix.version == 'WithFeatures'
        run: |
          sed -e '/^##.*$/d' -e '/^$/d' config.addon.seed >> openwrt/.config

      - name: Make Config
        run: |
          cd openwrt
          make defconfig
          chmod -R 755 ./

      - name: Setup Debug Session
        if: env.ssh_debug == 'true'
        uses: P3TERX/debugger-action@master

      - name: Set Build Time
        id: set_time
        run: |
          build_time=$(date +%Y-%m-%dT%H-%M)
          echo -e "\033[32m\033[1m$build_time\033[0m"
          echo "##[set-output name=build_time;]$build_time"

      - name: Make Toolchain
        run: |
          cd openwrt
          let make_process=$(nproc)+1
          make toolchain/install -j${make_process} V=s

      - name: Compile Openwrt
        run: |
          cd openwrt
          let make_process=$(nproc)+1
          make -j${make_process} V=s || make -j${make_process} V=s

      - name: Zip Files
        run: |
          rm -rf artifact
          mkdir artifact
          cd openwrt/bin/targets/rockchip/armv8
          #rm -rf `ls | grep -v "squashfs"`
          gzip -d *.gz
          gzip *.img
          mv * ../../../../../artifact
          cd ../../../../../artifact
          zip ../R2S-${{ steps.set_name.outputs.username }}-${{ matrix.version }}-${{ steps.set_time.outputs.build_time }}-ROM.zip * .*

      - name: Upload Artifact
        continue-on-error: true
        uses: actions/upload-artifact@master
        with:
          name: R2S-${{ steps.set_name.outputs.username }}-${{ matrix.version }}-${{ steps.set_time.outputs.build_time }}-ROM
          path: ./artifact/

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "R2S-${{ steps.set_name.outputs.username }}-*-ROM.zip,artifact/config.seed"
          body: Built at ${{ steps.set_time.outputs.build_time }} for ${{ matrix.version }}
          commit: ${{ github.sha }}
          name: R2S-${{ steps.set_name.outputs.username }}-${{ matrix.version }}-${{ steps.set_time.outputs.build_time }}
          tag: ${{ matrix.version }}-${{ steps.set_time.outputs.build_time }}
          token: ${{ secrets.sec_token }}
