name: R2S FriendlyWrt

on:
  push:
    branches:
      - master

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master

      - name: Initialization Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo rm -rf /etc/apt/sources.list.d
          sudo apt-get update
          sudo apt-get -y --no-install-recommends install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler
          curl https://raw.githubusercontent.com/friendlyarm/build-env-on-ubuntu-bionic/master/install.sh  | sed '/#/d' | sed 's/\\//g' | sed 's/exit 0//g' | sed 's/sudo apt -y install//g' | sed 's/sudo apt-get -y install//g' | sed 's/:i386//g' | xargs sudo apt-get -y --no-install-recommends install
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android/sdk

      - name: Init Source
        run: |
          git clone https://github.com/friendlyarm/repo
          sudo cp repo/repo /usr/bin/
          mkdir friendlywrt-rk3328
          cd friendlywrt-rk3328
          repo init -u https://github.com/friendlyarm/friendlywrt_manifests -b master-v19.07.1 -m rk3328.xml --repo-url=https://github.com/friendlyarm/repo --no-clone-bundle --depth=1
          repo sync -c --no-tags --no-clone-bundle -j8
          cd friendlywrt/
          git fetch --unshallow

      - name: Patch Kernel
        run: |
          cd friendlywrt-rk3328/kernel/
          git apply ../../add_fullconenat.diff
          wget https://github.com/armbian/build/raw/master/patch/kernel/rockchip64-dev/RK3328-enable-1512mhz-opp.patch
          git apply RK3328-enable-1512mhz-opp.patch
          cd ../
          git clone https://github.com/openwrt/openwrt
          cd openwrt/
          rm target/linux/generic/pending-5.4/403-mtd-hook-mtdsplit-to-Kbuild.patch
          rm target/linux/generic/hack-5.4/700-swconfig_switch_drivers.patch
          ./scripts/patch-kernel.sh ../kernel target/linux/generic/backport-5.4
          ./scripts/patch-kernel.sh ../kernel target/linux/generic/pending-5.4
          ./scripts/patch-kernel.sh ../kernel target/linux/generic/hack-5.4
          cd ../
          wget https://github.com/torvalds/linux/raw/master/scripts/kconfig/merge_config.sh && chmod +x merge_config.sh
          grep -i '_NETFILTER_\|FLOW' ../config.override > .config.override
          ./merge_config.sh -m .config.override kernel/arch/arm64/configs/nanopi-r2_linux_defconfig
          mv .config kernel/arch/arm64/configs/nanopi-r2_linux_defconfig
          sed -i -r 's/# (CONFIG_.*_ERRATUM_.*?) is.*/\1=y/g' kernel/arch/arm64/configs/nanopi-r2_linux_defconfig

      - name: Merge Lean's version and Lienol's version to original OpenWrt
        run: |
          chosen_date="2020-03-28 08:09:00"   # The time should match Dayong's cron time. The date is changeable.
          cd friendlywrt-rk3328/friendlywrt
          git config --local user.email "action@github.com" && git config --local user.name "GitHub Action"
          git remote add upstream https://github.com/Lienol/openwrt && git fetch upstream
          lede_hash=$(git log --before="$chosen_date" -1 --pretty=format:"%H" upstream/dev-lean-lede)
          git checkout $lede_hash -b tmp      # upstream/dev-lean-lede | https://github.com/Lienol/openwrt/commits/dev-lean-lede
          [ -f README.md ] && (git rm README.md)
          [ ! -f README ] && (touch README && git add README)
          git commit -m 'Prepare README for rebasing'
          friendlywrt_hash=$(git log --before="$chosen_date" -1 --pretty=format:"%H" origin/master-v19.07.1)
          git checkout $friendlywrt_hash      # origin/master-v19.07.1 | https://github.com/friendlyarm/friendlywrt/commits/master-v19.07.1
          git rebase adc1a9a3676b8d7be1b48b5aed185a94d8e42728^ --onto tmp -X theirs
          git checkout upstream/dev-lean-lede -- feeds.conf.default
          git apply ../../enable_autocore.diff
          sed -i '/exit/i\chown -R root:root /usr/share/netdata/web' package/lean/default-settings/files/zzz-default-settings
          sed -i 's/option fullcone\t1/option fullcone\t0/' package/network/config/firewall/files/firewall.config
          sed -i '/8.8.8.8/d' package/base-files/files/root/setup.sh

      - name: Generate config
        run: |
          cd friendlywrt-rk3328
          find device/ -name distfeeds.conf -delete
          sed '/Base_RK3328/,$d' ../config.seed > app_config
          grep -f app_config -v -F -x ../config.seed > base_config
          cat configs/config_rk3328 | grep "TARGET" >> base_config
          cat app_config >> base_config
          sed -e '/^#.*$/d' -e '/^$/d' base_config > configs/config_rk3328
          rm base_config app_config

      - name: Add checkwan script
        run: |
          git clone https://github.com/lsl330/R2S-SCRIPTS
          mv R2S-SCRIPTS/checkwan.sh friendlywrt-rk3328/friendlywrt/package/base-files/files/usr/bin
          rm -rf R2S-SCRIPTS
          cd friendlywrt-rk3328/friendlywrt/package/base-files/files
          chmod +x usr/bin/checkwan.sh
          sed -i '/exit/i\nohup /bin/sh /usr/bin/checkwan.sh  1>/dev/null 2>&1 &' etc/rc.local

      - name: Add auto update script
        run: |
          cd friendlywrt-rk3328/friendlywrt/package/base-files/files
          mv ../../../../../autoupdate.sh root/au && chmod +x root/au

      - name: Upgrade Argon theme
        run: |
          cd friendlywrt-rk3328/friendlywrt/package
          rm -rf lean/luci-theme-argon
          git clone -b 18.06 https://github.com/jerrykuku/luci-theme-argon.git
          sed -i '/uci commit luci/i\uci set luci.main.mediaurlbase="/luci-static/argon"' lean/default-settings/files/zzz-default-settings

      - name: Add Luci-R2SFlasher
        run: |
          git clone https://github.com/songchenwen/nanopi-r2s
          mv nanopi-r2s/luci-app-r2sflasher friendlywrt-rk3328/friendlywrt/package
          rm -rf nanopi-r2s

      - name: Add OpenClash
        run: |
          git clone https://github.com/vernesong/OpenClash.git
          mv OpenClash/luci-app-openclash friendlywrt-rk3328/friendlywrt/package
          rm -rf OpenClash
          cd friendlywrt-rk3328/friendlywrt/package/base-files/files
          mkdir -p etc/openclash && cd etc/openclash
          curl -L https://github.com/vernesong/OpenClash/releases/download/Clash/clash-linux-armv8.tar.gz | tar zxf -
          chmod +x clash

      - name: Add AdGuard Home
        run: |
          cd friendlywrt-rk3328/friendlywrt/package
          git clone https://github.com/rufengsuixing/luci-app-adguardhome.git

      - name: Add Serverchan
        run: |
          cd friendlywrt-rk3328/friendlywrt/package
          git clone https://github.com/tty228/luci-app-serverchan.git

      - name: Build
        run: |
          cd friendlywrt-rk3328
          sed -i 's/set -eu/set -u/' scripts/mk-friendlywrt.sh
          ./build.sh nanopi_r2s.mk

      - name: Fix FriendlyWrt rootfs owner and group
        run: |
          sudo losetup -o 100663296 /dev/loop99 friendlywrt-rk3328/out/*.img
          sudo rm -rf /mnt/friendlywrt-tmp
          sudo mkdir -p /mnt/friendlywrt-tmp
          sudo mount /dev/loop99 /mnt/friendlywrt-tmp
          sudo chown -R root:root /mnt/friendlywrt-tmp
          sudo umount /mnt/friendlywrt-tmp
          sudo losetup -d /dev/loop99

      - name: Zip Files
        id: zip_file
        run: |
          rm -rf ./artifact/
          mkdir -p ./artifact/
          gzip friendlywrt-rk3328/out/*.img
          mv friendlywrt-rk3328/out/*img* ./artifact/
          cp friendlywrt-rk3328/friendlywrt/.config ./artifact/config.seed
          cd artifact
          commit_time=$(date --iso-8601=date --date "$(git show -s --format=%ci $GITHUB_SHA | cut -d \  -f -2)")
          zip ../R2S-Gyj1109-$commit_time-ROM.zip *
          echo "##[set-output name=date_today;]$commit_time"

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: R2S-Gyj1109-*-ROM.zip
          artifactContentType: application/zip
          name: R2S-Gyj1109-${{ steps.zip_file.outputs.date_today }}
          tag: ${{ steps.zip_file.outputs.date_today }}
          token: ${{ secrets.sec_token }}
